### ISSUE TITLE
Support SSO auth

### ISSUE THREAD

**Issue by spaetz** [element-hq/hydrogen-web#274] opened 2021-03-15 12:11 UTC
I love hydrogen, but using it with matrix.debian.social is impossible. it only supports single sign on (SSO) auth and not direct password login. It would be awesome if SSO auth could be supported (or I could at least inject an auth token somehow).

**Comment by bwindels** [comment] 2021-03-15 12:37
Duplicate of #93

**Closed as completed by bwindels** 2021-03-15 12:37 UTC

**Comment by spaetz** [comment] 2021-03-15 15:16
Uhh, sorry. I am sure I searched for the issue before filing, but I must have missed the real one. I apologize.
